apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: python9224github
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python9224github 
  name: python9224github
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: python9224github 
